# Generated by Django 5.1.7 on 2025-03-31 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.ImageField(upload_to='edited/')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.imageupload')),
            ],
        ),
    ]
