# Generated by Django 5.1.7 on 2025-04-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_editedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='labels',
            field=models.JSONField(default=list),
        ),
    ]
