# Generated by Django 5.1.7 on 2025-05-27 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_imageupload_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRestorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.ImageField(upload_to='restore/')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imageapp.imageupload')),
            ],
        ),
    ]
