# Generated by Django 5.1.7 on 2025-05-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_imagerestorepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedimage',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
    ]
