# Generated by Django 5.1.7 on 2025-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0005_editedimage_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
