# Generated by Django 5.1.7 on 2025-05-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0006_imageupload_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_location', models.JSONField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.facecluster')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.imageupload')),
            ],
        ),
    ]
