# Generated by Django 5.1.7 on 2025-05-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0007_facecluster_facematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
                ('group_id', models.IntegerField(null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.imageupload')),
            ],
        ),
    ]
