# Generated by Django 5.1.7 on 2025-05-27 19:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0008_faceencoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='imageapp.imageupload')),
            ],
        ),
    ]
