# Generated by Django 5.1.7 on 2025-06-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0010_imageupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='clustered',
            field=models.BooleanField(default=False),
        ),
    ]
