# Generated by Django 5.1.7 on 2025-06-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0011_faceembedding_clustered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facematch',
            name='face_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
